### ISSUE TITLE
Non-dollar Math supported by MathJax is not processed by MathJax-node

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc-tex2svg#1]
Markdown:

```markdown
\begin{equation}
E = mc^2
\end{equation}

\begin{equation}
E = pc
\end{equation}
```

Command:

```bash
pandoc --mathjax -F pandoc-tex2svg
```

The resultant HTML is untouched by MathJax-node.

And by the way, the same test can be used to test AMS equation numbering. Because it is rendered by `mj-single.js`, I expect it not able to increment the numbering. I'm not sure what's the solution though (besides using `mj-page.js` which is supposed to work on HTML5 output. But obviously the one need this most is ePub output. I'm now thinking if it is possible to throw in the whole HTML file *before* combining it to ePub. However, I don't know the pandoc ePub build process so I don't know if it is possible.) I should have thought about this point before suggesting passing each equation to `tex2svg` rather than `page2svg`. I thought this is more robust, but now we lost AMS-numbering... Sorry!

**Comment by ickc** [comment]
Concerning applying `page2svg` on the individual `.xhtml` file extracted from ePub: it is a dead end, `error on line 117 at column 16: Opening and ending tag mismatch: link line 0 and head` keep popping up. I guess the XHTML confuses it.

**Comment by jgm** [comment]
This is really out of scope, since pandoc parses the equation environment as raw TeX and *not* as a Math element.  (For this reason, it won't work in any output format that doesn't know how to handle raw TeX.)

Ultimately pandoc needs to implement its own system for equation numbering, but that's another matter.
